### ISSUE TITLE
Module name change is breaking

### ISSUE THREAD

**Issue by axw** [xdg-go/stringprep#4]
In v1.0.1, the module name changed from github.com/xdg/stringprep to github.com/xdg-go/stringprep: https://github.com/xdg-go/stringprep/commit/f0136cbdfa821eb28ba74268131550989fd9f142

If another module has a dependency on github.com/xdg/stringprep v1.0.0 and one runs `go get -u`, it will break like so:

```
$ go get -u go.elastic.co/apm/module/apmmongo
go get: github.com/xdg/stringprep@v1.0.0 updating to
	github.com/xdg/stringprep@v1.0.1: parsing go.mod:
	module declares its path as: github.com/xdg-go/stringprep
	        but was required as: github.com/xdg/stringprep
```

This is happening because GitHub redirects `github.com/xdg/stringprep => github.com/xdg-go/stringprep`. Given that there's a redirect in place, perhaps the old module name could be reinstated? Alternatively starting a new major version should avoid this.

**Comment by mmuoDev** [comment]
Please can this be fixed?

**Comment by pierrre** [comment]
FYI I fixed it by adding this replace in my `go.mod`:
```
replace github.com/xdg/stringprep => github.com/xdg-go/stringprep v1.0.0
```

It's not working with v1.0.1, I don't know why, I don't want to know why.

Please fix it.
This package is used by the MongoDB driver.
IMO the right solution is to keep the "non Go module" version in the `xdg` org, and duplicate the repository in `xdg-go`
Or maybe create a fork from xdg-go to xdg, I don't know.

**Comment by pierrre** [comment]
@xdg do you have any news ?
I think the dependencies are broken for all users of the MongoDB driver.

**Comment by xdg** [comment]
Sorry for the late reply.  I never got an email notification from Github on the initial issue.  Stringprep was never a module so I'm surprised that `go get -u` is trying to upgrade based on repo/tag alone.  If you omit `-u` does it work?

**Comment by xdg** [comment]
I've recreated 'xdg/stringprep' at the v1.0.0 tag.

**Comment by srPuebla** [comment]
> Sorry for the late reply. I never got an email notification from Github on the initial issue. Stringprep was never a module so I'm surprised that `go get -u` is trying to upgrade based on repo/tag alone. If you omit `-u` does it work?

Yeah, if you remove -u it works fine, but i think that is not the correct way to solve this.

**Comment by rubengp99** [comment]
Hey @xdg, this is also happening for the `scram` package. There are a couple of issues opened

**Comment by caruccio** [comment]
https://github.com/percona/mongodb_exporter via https://github.com/percona/percona-toolkit is also suffering from this rename

**Comment by xdg** [comment]
Please let me know if it's still a problem, as `xdg/scram` and `xdg/stringprep` now exist again.  Also, the MongoDB Go driver 1.5.1 was just released with updated dependency information.

**Comment by pierrre** [comment]
It seems to work.
Thank you very much ! :+1:

**Comment by xdg** [comment]
I've also done a retrospective on what happened: https://xdg.me/i-broke-the-mongodb-go-driver-ecosystem/

**Comment by caruccio** [comment]
I can confirm https://github.com/percona/mongodb_exporter is working again. Thanks for your efforts.
